import pdf from'pdf-parse';import mammoth from'mammoth';import type{DatabaseClient}from'../db/supabase.js';import{HttpError}from'../utils/http-error.js';import{behavior}from'./runtime-settings.service.js';import{loadOwnerSettings}from'./owner-settings.service.js';import{createEmbeddingProvider}from'../providers/embedding/index.js';import type{EmbeddingProvider}from'../providers/embedding/embedding-provider.interface.js';import{recordUsageEvent}from'./usage.service.js';import{reserveKnowledgeIndex}from'./knowledge-index-rate-limit.js';import{KNOWLEDGE_DEFAULTS}from'../config/knowledge.js';
const allowed=new Set(['text/plain','text/markdown','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
export async function listKnowledgeDocuments(db:DatabaseClient,tenantId:string){const r=await db.from('knowledge_documents').select('id,file_name,media_type,size_bytes,page_count,character_count,status,error_code,embedding_model,created_at,updated_at').eq('tenant_id',tenantId).order('created_at',{ascending:false});if(r.error)throw new Error('Knowledge documents unavailable');return r.data??[]}
export async function deleteKnowledgeDocument(db:DatabaseClient,tenantId:string,id:string){const r=await db.from('knowledge_documents').delete().eq('tenant_id',tenantId).eq('id',id);if(r.error)throw new Error('Knowledge document delete failed')}
export async function indexKnowledgeDocument(db:DatabaseClient,tenantId:string,file:{name:string;type:string;data:Buffer},provider:EmbeddingProvider|null=createEmbeddingProvider()){
 const settings=behavior(await loadOwnerSettings(db,tenantId)),limits=knowledgeLimits(settings);if(!allowed.has(file.type))throw new HttpError(400,'Unsupported file type',{code:'knowledge_file_type'});if(file.data.length>limits.max_file_bytes)throw new HttpError(413,'File too large',{code:'knowledge_file_too_large'});
 const existing=await db.from('knowledge_documents').select('id,size_bytes',{count:'exact',head:false}).eq('tenant_id',tenantId);if(existing.error)throw new Error('Knowledge limits unavailable');if((existing.count??existing.data?.length??0)>=limits.max_files)throw new HttpError(429,'File count limit reached',{code:'knowledge_file_count_limit'});if((existing.data??[]).reduce((n,x)=>n+Number(x.size_bytes),0)+file.data.length>limits.max_total_bytes)throw new HttpError(429,'Storage limit reached',{code:'knowledge_storage_limit'});
 const reservation=await reserveKnowledgeIndex(tenantId,limits.indexing_hourly_limit,limits.indexing_daily_limit);if(!reservation.allowed)throw new HttpError(429,'Knowledge indexing limit reached',{code:'knowledge_index_limit'});if(!provider)throw new HttpError(503,'Embedding is unavailable',{code:'knowledge_embedding_unavailable'});
 const extracted=await extract(file);if(extracted.pages&&extracted.pages>limits.max_pdf_pages)throw new HttpError(400,'PDF has too many pages',{code:'knowledge_pdf_pages'});const text=clean(extracted.text);if(!text)throw new HttpError(422,'Image-only PDF',{code:'knowledge_scanned_pdf'});if(text.length>limits.max_characters)throw new HttpError(413,'Document text too long',{code:'knowledge_text_too_long'});
 const inserted=await db.from('knowledge_documents').insert({tenant_id:tenantId,file_name:file.name.slice(0,255),media_type:file.type,size_bytes:file.data.length,page_count:extracted.pages??null,character_count:text.length,extracted_text:text,status:'processing',embedding_model:provider.model,embedding_dimensions:provider.dimensions}).select('id').single();if(inserted.error||!inserted.data)throw new Error('Knowledge document create failed');const id=String(inserted.data.id);
 try{const chunks=chunk(text,KNOWLEDGE_DEFAULTS.chunk_characters,KNOWLEDGE_DEFAULTS.chunk_overlap),batch=await provider.embed(chunks,'RETRIEVAL_DOCUMENT');const rows=chunks.map((content,i)=>({tenant_id:tenantId,document_id:id,chunk_index:i,content,character_count:content.length,embedding_model:provider.model,embedding_dimensions:provider.dimensions,embedding:JSON.stringify(batch.vectors[i])}));const saved=await db.from('knowledge_chunks').insert(rows);if(saved.error)throw new Error('Knowledge chunks create failed');await db.from('knowledge_documents').update({status:'ready',updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id);await recordUsageEvent(db,{tenantId,eventType:'embedding_call',quantity:batch.inputTokens??Math.ceil(text.length/4),metadata:{purpose:'knowledge_embedding_index',model:provider.model,dimensions:provider.dimensions,document_id:id,billable_message:false}});return{id,status:'ready',chunks:chunks.length};}catch(error){await db.from('knowledge_documents').update({status:'failed',error_code:'index_failed',updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id);throw error}
}
export async function reindexKnowledgeDocument(db:DatabaseClient,tenantId:string,id:string,provider:EmbeddingProvider|null=createEmbeddingProvider()){
 if(!provider)throw new HttpError(503,'Embedding is unavailable',{code:'knowledge_embedding_unavailable'});const doc=await db.from('knowledge_documents').select('id,extracted_text').eq('tenant_id',tenantId).eq('id',id).maybeSingle();if(doc.error||!doc.data)throw new HttpError(404,'Knowledge document not found',{code:'knowledge_not_found'});const settings=behavior(await loadOwnerSettings(db,tenantId)),reservation=await reserveKnowledgeIndex(tenantId,settings.knowledge_indexing_hourly_limit,settings.knowledge_indexing_daily_limit);if(!reservation.allowed)throw new HttpError(429,'Knowledge indexing limit reached',{code:'knowledge_index_limit'});const text=String(doc.data.extracted_text),chunks=chunk(text),batch=await provider.embed(chunks,'RETRIEVAL_DOCUMENT');const removed=await db.from('knowledge_chunks').delete().eq('tenant_id',tenantId).eq('document_id',id);if(removed.error)throw new Error('Old knowledge chunks delete failed');const saved=await db.from('knowledge_chunks').insert(chunks.map((content,i)=>({tenant_id:tenantId,document_id:id,chunk_index:i,content,character_count:content.length,embedding_model:provider.model,embedding_dimensions:provider.dimensions,embedding:JSON.stringify(batch.vectors[i])})));if(saved.error)throw new Error('Knowledge reindex failed');await db.from('knowledge_documents').update({status:'ready',error_code:null,embedding_model:provider.model,embedding_dimensions:provider.dimensions,updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id);await recordUsageEvent(db,{tenantId,eventType:'embedding_call',quantity:batch.inputTokens??Math.ceil(text.length/4),metadata:{purpose:'knowledge_embedding_index',model:provider.model,dimensions:provider.dimensions,document_id:id,reindex:true,billable_message:false}});return{id,status:'ready',chunks:chunks.length}
}
async function extract(file:{type:string;data:Buffer}){if(file.type==='application/pdf'){const result=await pdf(file.data);return{text:result.text,pages:result.numpages}}if(file.type.includes('wordprocessingml')){const result=await mammoth.extractRawText({buffer:file.data});return{text:result.value}}return{text:file.data.toString('utf8')}}
function clean(text:string){return text.replace(/\0/g,'').replace(/\r\n?/g,'\n').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim()}
function knowledgeLimits(settings:ReturnType<typeof behavior>){return{max_files:settings.knowledge_max_files,max_file_bytes:settings.knowledge_max_file_bytes,max_total_bytes:settings.knowledge_max_total_bytes,max_pdf_pages:settings.knowledge_max_pdf_pages,max_characters:settings.knowledge_max_characters,indexing_hourly_limit:settings.knowledge_indexing_hourly_limit,indexing_daily_limit:settings.knowledge_indexing_daily_limit}}
export function chunk(text:string,size=1200,overlap=200){const out:string[]=[];for(let start=0;start<text.length;){let end=Math.min(text.length,start+size);if(end<text.length){const boundary=Math.max(text.lastIndexOf('\n',end),text.lastIndexOf('. ',end));if(boundary>start+size/2)end=boundary+1}const value=text.slice(start,end).trim();if(value)out.push(value);if(end>=text.length)break;start=Math.max(start+1,end-overlap)}return out}
