import assert from 'node:assert/strict';
import test from 'node:test';
import { simulateCustomerMessage } from './simulator.service.js';
import type { AIProvider } from '../providers/ai/ai-provider.interface.js';

type Row=Record<string,unknown>;
function dbHarness(knowledge:Row[]){const tables:Record<string,Row[]>={notification_settings:[{tenant_id:'tenant',owner_phone:null,owner_chat_id:null,quiet_hours_start:null,quiet_hours_end:null,mode:'mute_all',time_zone:'Asia/Jerusalem',auto_replies_paused:false,behavior:{enabled_agents:['SALE','SUPPORT'],intent_confidence_threshold:.7,reception_max_messages:0},templates:{}}],schedule_exceptions:[],assistant_profiles:[{tenant_id:'tenant',assistant_name:'Leya',allowed_languages:['ru'],tone:'friendly_professional'}],knowledge_items:knowledge,escalations:[],usage_events:[]};return{tables,from(table:string){let rows:Row[]=tables[table]??[];let write:Row|null=null;const q:any={select(){return q},eq(key:string,value:unknown){rows=rows.filter((row:Row)=>row[key]===value);return q},not(key:string){rows=rows.filter((row:Row)=>row[key]!=null);return q},in(){return q},order(){return q},limit(n:number){rows=rows.slice(0,n);return q},maybeSingle:async()=>({data:rows[0]??null,error:null}),then(resolve:(v:unknown)=>unknown){return Promise.resolve({data:write?[write]:rows,error:null}).then(resolve)},insert(value:Row){write=value;tables[table]??=[];tables[table]!.push(value);return q},update(){return q}};return q}} as any;}

test('simulator uses exact FAQ without model or customer records',async()=>{const db=dbHarness([{id:'faq',tenant_id:'tenant',type:'faq',question:'Сколько стоит?',answer:'500 шекелей',active:true}]);let calls=0;const ai:AIProvider={async generateReply(){calls++;return{text:'unused'}}};const result=await simulateCustomerMessage(db,'tenant','Сколько стоит?',ai);assert.equal(result.reply,'500 шекелей');assert.equal(calls,0);assert.equal(db.tables.clients,undefined);assert.equal(db.tables.conversations,undefined);});

test('simulator marks model usage and does not persist routing data',async()=>{const db=dbHarness([{id:'faq',tenant_id:'tenant',type:'faq',question:'Цена',answer:'500 шекелей',active:true}]);let calls=0;const ai:AIProvider={async generateReply(input){calls++;return input.systemPrompt.includes('классификатор')?{text:'{"agent":"SALE","confidence":0.9}',usage:{model:'test'}}:{text:'Стоимость указана в базе знаний.',usage:{model:'test'}}}};const result=await simulateCustomerMessage(db,'tenant','Хочу узнать подробности покупки',ai);assert.equal(result.agent,'SALE');assert.ok(calls>=1);assert.ok(db.tables.usage_events.some((row:Row)=>(row.metadata as Row)?.simulation===true));assert.equal(db.tables.unrecognized_routes,undefined);});
