import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import test from 'node:test';
import {PGlite} from '@electric-sql/pglite';
import type {AIProvider} from '../providers/ai/ai-provider.interface.js';
import type {DatabaseClient} from '../db/supabase.js';
import {simulateCustomerMessage} from './simulator.service.js';

type Filter={column:string;notNull?:boolean;value?:unknown};
class PgQuery{
 private columns='*';private filters:Filter[]=[];private maximum:number|null=null;private inserted:Record<string,unknown>|null=null;
 constructor(private db:PGlite,private table:string){}
 select(columns='*'){this.columns=columns;return this;} eq(column:string,value:unknown){this.filters.push({column,value});return this;}
 not(column:string,_operator:string,value:unknown){if(value===null)this.filters.push({column,notNull:true});return this;} order(){return this;} limit(value:number){this.maximum=value;return this;}
 insert(value:Record<string,unknown>){this.inserted=value;return this;} async maybeSingle(){const result=await this.execute();return{data:result.data?.[0]??null,error:result.error};}
 then(resolve:any,reject?:any){return this.execute().then(resolve,reject);}
 private async execute(){try{if(this.inserted){const keys=Object.keys(this.inserted),params=keys.map(key=>this.inserted![key]);await this.db.query(`insert into ${this.table}(${keys.join(',')}) values(${keys.map((_,i)=>'$'+(i+1)).join(',')})`,params);return{data:[this.inserted],error:null};}
  const params:unknown[]=[],where=this.filters.map(filter=>{if(filter.notNull)return`${filter.column} is not null`;params.push(filter.value);return`${filter.column}=$${params.length}`;}).join(' and '),result=await this.db.query(`select ${this.columns} from ${this.table}${where?' where '+where:''}${this.maximum!==null?' limit '+this.maximum:''}`,params);return{data:result.rows,error:null};
 }catch(error){throw error;}}
}
const adapter=(db:PGlite)=>({from:(table:string)=>new PgQuery(db,table)}) as unknown as DatabaseClient;
async function fixture(){const db=new PGlite();await db.exec(`create table notification_settings(tenant_id uuid primary key,owner_phone text,owner_chat_id text,owner_pairing_hash text,owner_pairing_expires_at timestamptz,quiet_hours_start time,quiet_hours_end time,mode text,time_zone text,auto_replies_paused boolean,translate_owner_answer boolean,behavior jsonb,templates jsonb);create table schedule_exceptions(id uuid,start_date date,end_date date,kind text,work_start time,work_end time,name text,recurs_annually boolean,tenant_id uuid);create table assistant_profiles(tenant_id uuid,assistant_name text,allowed_languages text[],tone text,mode text,system_rules text);create table knowledge_items(id uuid default gen_random_uuid(),tenant_id uuid,type text,question text,answer text,active boolean);create table escalations(id uuid default gen_random_uuid(),tenant_id uuid,conversation_id uuid,status text);create table usage_events(id uuid default gen_random_uuid(),tenant_id uuid,event_type text,quantity numeric,event_key text,agent text,metadata jsonb);`);const tenant='10000000-0000-4000-8000-000000000001';await db.query(`insert into notification_settings(tenant_id,mode,time_zone,auto_replies_paused,behavior,templates)values($1,'mute_all','Asia/Jerusalem',false,$2,'{}')`,[tenant,JSON.stringify({enabled_agents:['SALE','SUPPORT'],intent_confidence_threshold:.7,reception_max_messages:0,simulator_hourly_limit:30,simulator_daily_limit:100})]);await db.query("insert into assistant_profiles(tenant_id,assistant_name,allowed_languages,tone)values($1,'Leya',array['ru'],'friendly_professional')",[tenant]);return{db,tenant,client:adapter(db)};}

test('arbitrary non-FAQ simulation works against PostgreSQL UUID types without persistence',async()=>{const {db,tenant,client}=await fixture(),root=await mkdtemp(join(tmpdir(),'leya-sim-'));try{const ai:AIProvider={async generateReply(input){return input.systemPrompt.includes('классификатор')?{text:'{"agent":"SALE","confidence":0.9}'}:{text:'Стоимость зависит от выбранной услуги.'};}};const result=await simulateCustomerMessage(client,tenant,'Здравствуйте, сколько стоит консультация и как записаться?',ai,{root});assert.ok(result.reply.length>0);assert.equal((await db.query<{count:number}>('select count(*)::int count from escalations')).rows[0]!.count,0);assert.ok((await db.query<{count:number}>('select count(*)::int count from usage_events')).rows[0]!.count>=1);}finally{await db.close();await rm(root,{recursive:true,force:true});}});
test('exact FAQ avoids Gemini and customer usage events',async()=>{const {db,tenant,client}=await fixture(),root=await mkdtemp(join(tmpdir(),'leya-sim-'));try{await db.query("insert into knowledge_items(tenant_id,type,question,answer,active)values($1,'faq','Сколько стоит?','500 шекелей',true)",[tenant]);let calls=0;const ai:AIProvider={async generateReply(){calls++;return{text:'unused'}}};const result=await simulateCustomerMessage(client,tenant,'Сколько стоит?',ai,{root});assert.equal(result.reply,'500 шекелей');assert.equal(calls,0);assert.equal((await db.query<{count:number}>('select count(*)::int count from usage_events')).rows[0]!.count,0);}finally{await db.close();await rm(root,{recursive:true,force:true});}});
test('simulator enforces independent hourly and daily limits',async()=>{const {db,tenant,client}=await fixture(),root=await mkdtemp(join(tmpdir(),'leya-sim-'));try{await db.query("update notification_settings set behavior=behavior||'{\"simulator_hourly_limit\":1,\"simulator_daily_limit\":2}'::jsonb where tenant_id=$1",[tenant]);const ai:AIProvider={async generateReply(){return{text:'ok'}}};await simulateCustomerMessage(client,tenant,'Привет',ai,{root,now:new Date('2026-09-12T10:00:00Z')});await assert.rejects(simulateCustomerMessage(client,tenant,'Ещё',ai,{root,now:new Date('2026-09-12T10:10:00Z')}),/hourly/);await simulateCustomerMessage(client,tenant,'Позже',ai,{root,now:new Date('2026-09-12T11:00:00Z')});await assert.rejects(simulateCustomerMessage(client,tenant,'Снова',ai,{root,now:new Date('2026-09-12T12:00:00Z')}),/daily/);}finally{await db.close();await rm(root,{recursive:true,force:true});}});
test('simulator remains fully available while customer replies are paused',async()=>{const {db,tenant,client}=await fixture(),root=await mkdtemp(join(tmpdir(),'leya-sim-'));try{await db.query('update notification_settings set auto_replies_paused=true where tenant_id=$1',[tenant]);const ai:AIProvider={async generateReply(input){return input.systemPrompt.includes('классификатор')?{text:'{"agent":"SUPPORT","confidence":0.95}'}:{text:'Пробный ответ работает.'};}};const result=await simulateCustomerMessage(client,tenant,'Помогите с услугой',ai,{root});assert.ok(result.reply.length>0);assert.ok(['SUPPORT','RECEPTION'].includes(result.agent));}finally{await db.close();await rm(root,{recursive:true,force:true});}});
